// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrAVp-ovjCBiOgi3k0XGw6nUePYJwPDP0',
    appId: '1:699457902383:web:96032ae5faaf57b706f3da',
    messagingSenderId: '699457902383',
    projectId: 'farmayopin-laboratorio',
    authDomain: 'farmayopin-laboratorio.firebaseapp.com',
    storageBucket: 'farmayopin-laboratorio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBWM72--zqlLzdfFr5ro6pDJKoi7nEq0',
    appId: '1:699457902383:ios:9ea3da92174cced006f3da',
    messagingSenderId: '699457902383',
    projectId: 'farmayopin-laboratorio',
    storageBucket: 'farmayopin-laboratorio.firebasestorage.app',
    iosClientId: '699457902383-m2t6pv5i7s87m1av4dun2gak4vfdfg4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmayopinApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClBWM72--zqlLzdfFr5ro6pDJKoi7nEq0',
    appId: '1:699457902383:ios:9ea3da92174cced006f3da',
    messagingSenderId: '699457902383',
    projectId: 'farmayopin-laboratorio',
    storageBucket: 'farmayopin-laboratorio.firebasestorage.app',
    iosClientId: '699457902383-m2t6pv5i7s87m1av4dun2gak4vfdfg4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmayopinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrAVp-ovjCBiOgi3k0XGw6nUePYJwPDP0',
    appId: '1:699457902383:web:087e398bbb26fcc506f3da',
    messagingSenderId: '699457902383',
    projectId: 'farmayopin-laboratorio',
    authDomain: 'farmayopin-laboratorio.firebaseapp.com',
    storageBucket: 'farmayopin-laboratorio.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgjKlpj5tDzkjGqp0CoDEKa0lEYIXPmI',
    appId: '1:699457902383:android:0367955ac9b24ba306f3da',
    messagingSenderId: '699457902383',
    projectId: 'farmayopin-laboratorio',
    storageBucket: 'farmayopin-laboratorio.firebasestorage.app',
  );
}
